### ISSUE TITLE
Missing source files

### ISSUE THREAD

**Issue by Blaster1920** [tonyp7/esp32-nixie-clock#1]
Hi there,
I was interested in replicating your project for personal use, but I couldn't find anywhere in the repo the source files for the PCB and schematics.
Would you be able to upload them?
Thanks in advance.

**Comment by tonyp7** [comment]
Hello,

Yes I need to upload a few more files --including pictures of the final clock.  I'll do that this week!

Cheers

**Comment by tonyp7** [comment]
I added gerber files. I don't understand your comment about schematics though, it's all there (?)

**Comment by Blaster1920** [comment]
Hi there,
thanks for the reply and the gerbers.
What I meant is that it's missing the source files for the schematics,  the proprietary files of the CAD you've used (eg. Kicad .sch).  So I can modify it or export the BOM, which you didn't publish (yet).

**Comment by tonyp7** [comment]
I pushed the original file (Dip Trace) in /schematics and added the BOM. Good luck!

**Comment by Blaster1920** [comment]
> I pushed the original file (Dip Trace) in /schematics and added the BOM. Good luck!

Thanks for your help! I'll give it a try.
